### ISSUE TITLE
Instant Bow Kill Update.

### ISSUE THREAD

**Issue by FooFieOwO** [RanyoDevelopment/RanyoPublicStuff#10]
Convert InstantBowKill Module into an Module like this from Wurst xd | https://github.com/Wurst-Imperium/Wurst7/commit/fd5915bc3e03bc967ea361d5c23b51bafcef29e4

**Comment by ed0cinU** [comment]
Done!
![image](https://user-images.githubusercontent.com/58796076/167599998-c86000e1-f6ae-4352-9c88-8fb5469bd703.png)
