### ISSUE TITLE
Add Handshake IP Spoof (used for bungee sub server connect hack) 

### ISSUE THREAD

**Issue by FooFieOwO** [RanyoDevelopment/RanyoPublicStuff#17]
Add Handshake IP Spoof (used for bungee sub server connect hack)

**Comment by ed0cinU** [comment]
Done! uwu
![image](https://user-images.githubusercontent.com/58796076/165425810-b6d063a4-1961-44cc-8b7f-1c94e305fbfe.png)
![image](https://user-images.githubusercontent.com/58796076/165425847-adb14ee9-9777-48b7-afef-83c7f8e182ce.png)
