### ISSUE TITLE
Murder Mystery Freundes highlighting

### ISSUE THREAD

**Issue by Ranjid-Mod-Mod** [RanyoDevelopment/RanyoPublicStuff#35]
In dem Module sollte ein extra Option eingebaut werden dass Freunde in eine andere Farbe nochmals gehighlighted werden, wenn er Detective/Murder ist. Standartmässig sollte der Freundes Murder entweder (Hellrot, Orange oder Pink) und Freundes Detective (Grün oder Gelb) sein. Und als extra, dass man Murder, Detective bzw. Freundes Murder, Freundes Detective mit dem Highlight separat einstellbar ist, d.h. ich könnte z.b. als farbenblinder den Murder die Farbe Grün einstellen.

**Comment by ed0cinU** [comment]
The new Ranyo Mod will automatically fix this issue by not using Meteor.
