### ISSUE TITLE
Dropdown Menu im ProtocolConfig

### ISSUE THREAD

**Issue by Ranjid-Mod-Mod** [RanyoDevelopment/RanyoPublicStuff#40]
Bei der Dropdown Menu im ProtocolConfig für Protocol Version ist das scrollen vertauscht

**Comment by FlorianMichael** [comment]
we call it "Feature by Pascal"

**Comment by ed0cinU** [comment]
xD

**Comment by ed0cinU** [comment]
@FooFieOwO

**Comment by ed0cinU** [comment]
Das ist generell so bei den Dropdown boxen, ich versuchs jetzt zu fixen.

**Comment by ed0cinU** [comment]
habs gefixt xd
